# Generated by Django 6.0.4 on 2026-04-10 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accessrule',
            options={'verbose_name': 'Правило доступа', 'verbose_name_plural': 'Правила доступа'},
        ),
        migrations.AlterUniqueTogether(
            name='accessrule',
            unique_together={('role', 'element')},
        ),
    ]
