# Generated by Django 6.0.4 on 2026-04-13 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0002_alter_accessrule_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='is_default_role',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='is_guest',
            field=models.BooleanField(default=False),
        ),
    ]
