# Generated by Django 6.0.4 on 2026-04-14 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0003_role_is_default_role_role_is_guest'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesselement',
            name='is_system',
            field=models.BooleanField(default=False),
        ),
    ]
